<a href="https://colab.research.google.com/github/Doumgit/D602-Advance-Programming-Techniques/blob/main/SDoumbia_QOTW_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. What are the similarities and differences between pandas and numpy?   Include some type of example with code.



***Similarities:***

- Performance: Both libraries are built on C, ensuring efficient computation and data manipulation.
- Data Handling: They are used for handling numerical data and performing mathematical operations.
- Interoperability: Pandas relies on NumPy for its underlying data structures and operations, making them highly interoperable.

***Differences:***
- Data Structures: NumPy provides a fundamental structure, the ndarray, for handling numerical data. Pandas introduces more high-level data structures like **DataFrame** and **Series**, which are built on top of NumPy arrays and provide a more intuitive interface for handling tabular data.
- Functionality: NumPy is more focused on mathematical and numerical operations, such as matrix multiplication and transformations. Pandas, on the other hand, offers more sophisticated tools for data manipulation, such as merging, reshaping, and summarizing data.
- Use Cases: NumPy is more suited for numerical and scientific computing where complex mathematical operations are common. Pandas is designed for data analysis and manipulation, making it more suitable for working with structured data like CSV files or SQL query results.

**Example Code**

In [1]:
# Numpy Example
import numpy as np

# Creating a NumPy array
data = np.array([1, 2, 3, 4, 5])

# Computing the mean
mean = np.mean(data)
print("Mean with NumPy:", mean)


Mean with NumPy: 3.0


In [2]:
# Pandas Example
import pandas as pd

# Creating a Pandas Series
data = pd.Series([1, 2, 3, 4, 5])

# Computing the mean
mean = data.mean()
print("Mean with Pandas:", mean)


Mean with Pandas: 3.0


Both examples achieve the same result, but the Pandas example operates on a **Series** object.

### 2. What is the ndarray in numPy?



The **ndarray** in NumPy, short for n-dimensional array, is the fundamental data structure provided by the NumPy library for storing and manipulating homogeneous data. It is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions (axes) of the array is described by its shape, which is a tuple of integers indicating the size of the array along each dimension.

### 3. Create a 1D array of numbers from 0 to 9
Desired Output:

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
import numpy as np

# Creating a 1D array of numbers from 0 to 9
array_1d = np.arange(10)

array_1d


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 4. Extract all odd numbers from array1

array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import numpy as np

# Given array
array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extracting all odd numbers from array1
odd_numbers = array1[array1 % 2 == 1]

odd_numbers


array([1, 3, 5, 7, 9])

### 5. Get the common items between a and b  

***#input***

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

***#Desired Output:***

array([2, 4])

In [13]:
# Given input arrays
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Getting the common items between a and b
common_items = np.intersect1d(a, b)

common_items


array([2, 4])

### 6. From array a remove all items present in array b

###***Input:***

a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])

###***Desired Output:***

array([1,2,3,4])

In [14]:
import numpy as np

# Given input arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

# Removing all items in a that are present in b
result = np.setdiff1d(a, b)

result


array([1, 2, 3, 4])

### 7. Find out if iris has any missing values.



### ***Input***
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [17]:
import numpy as np

#Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


# Checking if there are any missing (NaN) values in the dataset
missing_values_exist = np.isnan(iris).any()

print("Are there any missing values in the Iris dataset?", missing_values_exist)

Are there any missing values in the Iris dataset? False
